{{- if and .Values.precedence.enabled (or .Values.serviceMonitor.enabled .Values.selfMetrics.enabled) }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "metrics-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "metrics-agent.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.serviceMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "metrics-agent.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: {{ .Values.status.metricsPath | quote }}
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
